name: mGiveaway
version: '0.5'
main: me.msuro.mGiveaway.MGiveaway
api-version: '1.13'
authors: [ mSuro_ ]
softdepend:
  - PlaceholderAPI
  - Vault

commands:
  mgwreload:
    description: Reloads the plugin
    usage: /mgwreload
    permission: mgiveaway.reload